{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "breath-dark",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#c86c85",
            "selected-text-color" : "#c86c85",
            "background-color" : "#292D2C"
        },
        "Annotation": {
            "text-color" : "#82a0a6",
            "selected-text-color" : "#82a0a6"
        },
        "Attribute" : {
            "text-color" : "#c669b5",
            "selected-text-color" : "#c669b5"
        },
        "BaseN": {
            "text-color" : "#c669b5",
            "selected-text-color" : "#c669b5"
        },
        "BuiltIn": {
            "text-color" : "#c86c85",
            "selected-text-color" : "#c86c85"
        },
        "Char": {
            "text-color" : "#c4cb71",
            "selected-text-color" : "#c4cb71"
        },
        "Comment": {
            "text-color" : "#82a0a6",
            "selected-text-color" : "#82a0a6"
        },
        "CommentVar" : {
            "text-color" : "#82a0a6",
            "selected-text-color" : "#82a0a6"
        },
        "Constant" : {
            "text-color" : "#73c2b2",
            "selected-text-color" : "#73c2b2"
        },
        "ControlFlow" : {
            "text-color" : "#66CF82",
            "selected-text-color" : "#66CF82"
        },
        "DataType" : {
            "text-color" : "#5B9BD6",
            "selected-text-color" : "#5B9BD6"
        },
        "DecVal" : {
            "text-color" : "#c669b5",
            "selected-text-color" : "#c669b5"
        },
        "Documentation" : {
            "text-color" : "#82a0a6",
            "selected-text-color" : "#82a0a6"
        },
        "Error" : {
            "text-color" : "#c86c85",
            "selected-text-color" : "#c86c85"
        },
        "Extension" : {
            "text-color" : "#c669b5",
            "selected-text-color" : "#c669b5"
        },
        "Float" : {
            "text-color" : "#c669b5",
            "selected-text-color" : "#c669b5"
        },
        "Function" : {
            "text-color" : "#c86c85",
            "selected-text-color" : "#c86c85"
        },
        "Import" : {
            "text-color" : "#5B9BD6",
            "selected-text-color" : "#5B9BD6"
        },
        "Information" : {
            "text-color" : "#82a0a6",
            "selected-text-color" : "#82a0a6"
        },
        "Keyword" : {
            "text-color" : "#66CF82",
            "selected-text-color" : "#66CF82"
        },
        "Normal" : {
            "text-color" : "#b4c7ca",
            "selected-text-color" : "#b4c7ca",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#73c2b2",
            "selected-text-color" : "#73c2b2"
        },
        "Others" : {
            "text-color" : "#c669b5",
            "selected-text-color" : "#c669b5"
        },
        "Preprocessor" : {
            "text-color" : "#5B9BD6",
            "selected-text-color" : "#5B9BD6"
        },
        "RegionMarker" : {
            "text-color" : "#5B9BD6",
            "selected-text-color" : "#5B9BD6"
        },
        "SpecialChar" : {
            "text-color" : "#c4cb71",
            "selected-text-color" : "#c4cb71"
        },
        "SpecialString" : {
            "text-color" : "#c4cb71",
            "selected-text-color" : "#c4cb71"
        },
        "String" : {
            "text-color" : "#c4cb71",
            "selected-text-color" : "#c4cb71"
        },
        "Variable" : {
            "text-color" : "#73c2b2",
            "selected-text-color" : "#73c2b2"
        },
        "VerbatimString" : {
            "text-color" : "#c4cb71",
            "selected-text-color" : "#c4cb71"
        },
        "Warning" : {
            "text-color" : "#c86c85",
            "selected-text-color" : "#c86c85"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#292D2C",
        "BracketMatching" : "#6F7A67",
        "CodeFolding" : "#6F7A67",
        "CurrentLine" : "#5E6757",
        "CurrentLineNumber" : "#82a0a6",
        "IconBorder" : "#353A39",
        "IndentationLine" : "#82a0a6",
        "LineNumbers" : "#82a0a6",
        "MarkBookmark" : "#66CF82",
        "MarkBreakpointActive" : "#66CF82",
        "MarkBreakpointDisabled" : "#6F7A67",
        "MarkBreakpointReached" : "#c669b5",
        "MarkError" : "#c86c85",
        "MarkExecution" : "#6F7A67",
        "MarkWarning" : "#c4cb71",
        "ModifiedLines" : "#c86c85",
        "ReplaceHighlight" : "#6F7A67",
        "SavedLines" : "#66CF82",
        "SearchHighlight" : "#6F7A67",
        "Separator" : "#292D2C",
        "SpellChecking" : "#c86c85",
        "TabMarker" : "#353A39",
        "TemplateBackground" : "#414845",
        "TemplateFocusedPlaceholder" : "#c669b5",
        "TemplatePlaceholder" : "#66CF82",
        "TemplateReadOnlyPlaceholder" : "#c4cb71",
        "TextSelection" : "#6F7A67",
        "WordWrapMarker" : "#414845"
    }
}
