{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "cryochamber",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#C08A9D",
            "selected-text-color" : "#C08A9D",
            "background-color" : "#1C1A17"
        },
        "Annotation": {
            "text-color" : "#899481",
            "selected-text-color" : "#899481"
        },
        "Attribute" : {
            "text-color" : "#C08ABF",
            "selected-text-color" : "#C08ABF"
        },
        "BaseN": {
            "text-color" : "#C08ABF",
            "selected-text-color" : "#C08ABF"
        },
        "BuiltIn": {
            "text-color" : "#C08A9D",
            "selected-text-color" : "#C08A9D"
        },
        "Char": {
            "text-color" : "#DBAD70",
            "selected-text-color" : "#DBAD70"
        },
        "Comment": {
            "text-color" : "#899481",
            "selected-text-color" : "#899481"
        },
        "CommentVar" : {
            "text-color" : "#899481",
            "selected-text-color" : "#899481"
        },
        "Constant" : {
            "text-color" : "#8AC0A1",
            "selected-text-color" : "#8AC0A1"
        },
        "ControlFlow" : {
            "text-color" : "#AFC08A",
            "selected-text-color" : "#AFC08A"
        },
        "DataType" : {
            "text-color" : "#8AB1C0",
            "selected-text-color" : "#8AB1C0"
        },
        "DecVal" : {
            "text-color" : "#C08ABF",
            "selected-text-color" : "#C08ABF"
        },
        "Documentation" : {
            "text-color" : "#899481",
            "selected-text-color" : "#899481"
        },
        "Error" : {
            "text-color" : "#C08A9D",
            "selected-text-color" : "#C08A9D"
        },
        "Extension" : {
            "text-color" : "#C08ABF",
            "selected-text-color" : "#C08ABF"
        },
        "Float" : {
            "text-color" : "#C08ABF",
            "selected-text-color" : "#C08ABF"
        },
        "Function" : {
            "text-color" : "#C08A9D",
            "selected-text-color" : "#C08A9D"
        },
        "Import" : {
            "text-color" : "#8AB1C0",
            "selected-text-color" : "#8AB1C0"
        },
        "Information" : {
            "text-color" : "#899481",
            "selected-text-color" : "#899481"
        },
        "Keyword" : {
            "text-color" : "#AFC08A",
            "selected-text-color" : "#AFC08A"
        },
        "Normal" : {
            "text-color" : "#c0c9af",
            "selected-text-color" : "#c0c9af",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#8AC0A1",
            "selected-text-color" : "#8AC0A1"
        },
        "Others" : {
            "text-color" : "#C08ABF",
            "selected-text-color" : "#C08ABF"
        },
        "Preprocessor" : {
            "text-color" : "#8AB1C0",
            "selected-text-color" : "#8AB1C0"
        },
        "RegionMarker" : {
            "text-color" : "#8AB1C0",
            "selected-text-color" : "#8AB1C0"
        },
        "SpecialChar" : {
            "text-color" : "#DBAD70",
            "selected-text-color" : "#DBAD70"
        },
        "SpecialString" : {
            "text-color" : "#DBAD70",
            "selected-text-color" : "#DBAD70"
        },
        "String" : {
            "text-color" : "#DBAD70",
            "selected-text-color" : "#DBAD70"
        },
        "Variable" : {
            "text-color" : "#8AC0A1",
            "selected-text-color" : "#8AC0A1"
        },
        "VerbatimString" : {
            "text-color" : "#DBAD70",
            "selected-text-color" : "#DBAD70"
        },
        "Warning" : {
            "text-color" : "#C08A9D",
            "selected-text-color" : "#C08A9D"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#1C1A17",
        "BracketMatching" : "#646d5d",
        "CodeFolding" : "#646d5d",
        "CurrentLine" : "#545b4e",
        "CurrentLineNumber" : "#899481",
        "IconBorder" : "#282622",
        "IndentationLine" : "#899481",
        "LineNumbers" : "#899481",
        "MarkBookmark" : "#AFC08A",
        "MarkBreakpointActive" : "#AFC08A",
        "MarkBreakpointDisabled" : "#646d5d",
        "MarkBreakpointReached" : "#C08ABF",
        "MarkError" : "#C08A9D",
        "MarkExecution" : "#646d5d",
        "MarkWarning" : "#DBAD70",
        "ModifiedLines" : "#C08A9D",
        "ReplaceHighlight" : "#646d5d",
        "SavedLines" : "#AFC08A",
        "SearchHighlight" : "#646d5d",
        "Separator" : "#1C1A17",
        "SpellChecking" : "#C08A9D",
        "TabMarker" : "#282622",
        "TemplateBackground" : "#38342F",
        "TemplateFocusedPlaceholder" : "#C08ABF",
        "TemplatePlaceholder" : "#AFC08A",
        "TemplateReadOnlyPlaceholder" : "#DBAD70",
        "TextSelection" : "#646d5d",
        "WordWrapMarker" : "#38342F"
    }
}
