{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "cryogenic",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#DC8896",
            "selected-text-color" : "#DC8896",
            "background-color" : "#3a3d34"
        },
        "Annotation": {
            "text-color" : "#abbfc4",
            "selected-text-color" : "#abbfc4"
        },
        "Attribute" : {
            "text-color" : "#C193D1",
            "selected-text-color" : "#C193D1"
        },
        "BaseN": {
            "text-color" : "#C193D1",
            "selected-text-color" : "#C193D1"
        },
        "BuiltIn": {
            "text-color" : "#DC8896",
            "selected-text-color" : "#DC8896"
        },
        "Char": {
            "text-color" : "#DCD587",
            "selected-text-color" : "#DCD587"
        },
        "Comment": {
            "text-color" : "#abbfc4",
            "selected-text-color" : "#abbfc4"
        },
        "CommentVar" : {
            "text-color" : "#abbfc4",
            "selected-text-color" : "#abbfc4"
        },
        "Constant" : {
            "text-color" : "#93B2D0",
            "selected-text-color" : "#93B2D0"
        },
        "ControlFlow" : {
            "text-color" : "#93D0A2",
            "selected-text-color" : "#93D0A2"
        },
        "DataType" : {
            "text-color" : "#9398D0",
            "selected-text-color" : "#9398D0"
        },
        "DecVal" : {
            "text-color" : "#C193D1",
            "selected-text-color" : "#C193D1"
        },
        "Documentation" : {
            "text-color" : "#abbfc4",
            "selected-text-color" : "#abbfc4"
        },
        "Error" : {
            "text-color" : "#DC8896",
            "selected-text-color" : "#DC8896"
        },
        "Extension" : {
            "text-color" : "#C193D1",
            "selected-text-color" : "#C193D1"
        },
        "Float" : {
            "text-color" : "#C193D1",
            "selected-text-color" : "#C193D1"
        },
        "Function" : {
            "text-color" : "#DC8896",
            "selected-text-color" : "#DC8896"
        },
        "Import" : {
            "text-color" : "#9398D0",
            "selected-text-color" : "#9398D0"
        },
        "Information" : {
            "text-color" : "#abbfc4",
            "selected-text-color" : "#abbfc4"
        },
        "Keyword" : {
            "text-color" : "#93D0A2",
            "selected-text-color" : "#93D0A2"
        },
        "Normal" : {
            "text-color" : "#b4e2ee",
            "selected-text-color" : "#b4e2ee",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#93B2D0",
            "selected-text-color" : "#93B2D0"
        },
        "Others" : {
            "text-color" : "#C193D1",
            "selected-text-color" : "#C193D1"
        },
        "Preprocessor" : {
            "text-color" : "#9398D0",
            "selected-text-color" : "#9398D0"
        },
        "RegionMarker" : {
            "text-color" : "#9398D0",
            "selected-text-color" : "#9398D0"
        },
        "SpecialChar" : {
            "text-color" : "#DCD587",
            "selected-text-color" : "#DCD587"
        },
        "SpecialString" : {
            "text-color" : "#DCD587",
            "selected-text-color" : "#DCD587"
        },
        "String" : {
            "text-color" : "#DCD587",
            "selected-text-color" : "#DCD587"
        },
        "Variable" : {
            "text-color" : "#93B2D0",
            "selected-text-color" : "#93B2D0"
        },
        "VerbatimString" : {
            "text-color" : "#DCD587",
            "selected-text-color" : "#DCD587"
        },
        "Warning" : {
            "text-color" : "#DC8896",
            "selected-text-color" : "#DC8896"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#3a3d34",
        "BracketMatching" : "#6f919b",
        "CodeFolding" : "#6f919b",
        "CurrentLine" : "#58767e",
        "CurrentLineNumber" : "#abbfc4",
        "IconBorder" : "#484a3f",
        "IndentationLine" : "#abbfc4",
        "LineNumbers" : "#abbfc4",
        "MarkBookmark" : "#93D0A2",
        "MarkBreakpointActive" : "#93D0A2",
        "MarkBreakpointDisabled" : "#6f919b",
        "MarkBreakpointReached" : "#C193D1",
        "MarkError" : "#DC8896",
        "MarkExecution" : "#6f919b",
        "MarkWarning" : "#DCD587",
        "ModifiedLines" : "#DC8896",
        "ReplaceHighlight" : "#6f919b",
        "SavedLines" : "#93D0A2",
        "SearchHighlight" : "#6f919b",
        "Separator" : "#3a3d34",
        "SpellChecking" : "#DC8896",
        "TabMarker" : "#484a3f",
        "TemplateBackground" : "#55584b",
        "TemplateFocusedPlaceholder" : "#C193D1",
        "TemplatePlaceholder" : "#93D0A2",
        "TemplateReadOnlyPlaceholder" : "#DCD587",
        "TextSelection" : "#6f919b",
        "WordWrapMarker" : "#55584b"
    }
}
