{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "millenium",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#da9694",
            "selected-text-color" : "#da9694",
            "background-color" : "#2f2a30"
        },
        "Annotation": {
            "text-color" : "#938696",
            "selected-text-color" : "#938696"
        },
        "Attribute" : {
            "text-color" : "#b1a0c7",
            "selected-text-color" : "#b1a0c7"
        },
        "BaseN": {
            "text-color" : "#b1a0c7",
            "selected-text-color" : "#b1a0c7"
        },
        "BuiltIn": {
            "text-color" : "#da9694",
            "selected-text-color" : "#da9694"
        },
        "Char": {
            "text-color" : "#fabf8f",
            "selected-text-color" : "#fabf8f"
        },
        "Comment": {
            "text-color" : "#938696",
            "selected-text-color" : "#938696"
        },
        "CommentVar" : {
            "text-color" : "#938696",
            "selected-text-color" : "#938696"
        },
        "Constant" : {
            "text-color" : "#92cddc",
            "selected-text-color" : "#92cddc"
        },
        "ControlFlow" : {
            "text-color" : "#c4d79b",
            "selected-text-color" : "#c4d79b"
        },
        "DataType" : {
            "text-color" : "#97b3d5",
            "selected-text-color" : "#97b3d5"
        },
        "DecVal" : {
            "text-color" : "#b1a0c7",
            "selected-text-color" : "#b1a0c7"
        },
        "Documentation" : {
            "text-color" : "#938696",
            "selected-text-color" : "#938696"
        },
        "Error" : {
            "text-color" : "#da9694",
            "selected-text-color" : "#da9694"
        },
        "Extension" : {
            "text-color" : "#b1a0c7",
            "selected-text-color" : "#b1a0c7"
        },
        "Float" : {
            "text-color" : "#b1a0c7",
            "selected-text-color" : "#b1a0c7"
        },
        "Function" : {
            "text-color" : "#da9694",
            "selected-text-color" : "#da9694"
        },
        "Import" : {
            "text-color" : "#97b3d5",
            "selected-text-color" : "#97b3d5"
        },
        "Information" : {
            "text-color" : "#938696",
            "selected-text-color" : "#938696"
        },
        "Keyword" : {
            "text-color" : "#c4d79b",
            "selected-text-color" : "#c4d79b"
        },
        "Normal" : {
            "text-color" : "#b6adb8",
            "selected-text-color" : "#b6adb8",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#92cddc",
            "selected-text-color" : "#92cddc"
        },
        "Others" : {
            "text-color" : "#b1a0c7",
            "selected-text-color" : "#b1a0c7"
        },
        "Preprocessor" : {
            "text-color" : "#97b3d5",
            "selected-text-color" : "#97b3d5"
        },
        "RegionMarker" : {
            "text-color" : "#97b3d5",
            "selected-text-color" : "#97b3d5"
        },
        "SpecialChar" : {
            "text-color" : "#fabf8f",
            "selected-text-color" : "#fabf8f"
        },
        "SpecialString" : {
            "text-color" : "#fabf8f",
            "selected-text-color" : "#fabf8f"
        },
        "String" : {
            "text-color" : "#fabf8f",
            "selected-text-color" : "#fabf8f"
        },
        "Variable" : {
            "text-color" : "#92cddc",
            "selected-text-color" : "#92cddc"
        },
        "VerbatimString" : {
            "text-color" : "#fabf8f",
            "selected-text-color" : "#fabf8f"
        },
        "Warning" : {
            "text-color" : "#da9694",
            "selected-text-color" : "#da9694"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#2f2a30",
        "BracketMatching" : "#695d6c",
        "CodeFolding" : "#695d6c",
        "CurrentLine" : "#554b57",
        "CurrentLineNumber" : "#938696",
        "IconBorder" : "#3b343d",
        "IndentationLine" : "#938696",
        "LineNumbers" : "#938696",
        "MarkBookmark" : "#c4d79b",
        "MarkBreakpointActive" : "#c4d79b",
        "MarkBreakpointDisabled" : "#695d6c",
        "MarkBreakpointReached" : "#b1a0c7",
        "MarkError" : "#da9694",
        "MarkExecution" : "#695d6c",
        "MarkWarning" : "#fabf8f",
        "ModifiedLines" : "#da9694",
        "ReplaceHighlight" : "#695d6c",
        "SavedLines" : "#c4d79b",
        "SearchHighlight" : "#695d6c",
        "Separator" : "#2f2a30",
        "SpellChecking" : "#da9694",
        "TabMarker" : "#3b343d",
        "TemplateBackground" : "#48404a",
        "TemplateFocusedPlaceholder" : "#b1a0c7",
        "TemplatePlaceholder" : "#c4d79b",
        "TemplateReadOnlyPlaceholder" : "#fabf8f",
        "TextSelection" : "#695d6c",
        "WordWrapMarker" : "#48404a"
    }
}
