{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "north-sea",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#C3755F",
            "selected-text-color" : "#C3755F",
            "background-color" : "#292F2C"
        },
        "Annotation": {
            "text-color" : "#95A39D",
            "selected-text-color" : "#95A39D"
        },
        "Attribute" : {
            "text-color" : "#AD7583",
            "selected-text-color" : "#AD7583"
        },
        "BaseN": {
            "text-color" : "#AD7583",
            "selected-text-color" : "#AD7583"
        },
        "BuiltIn": {
            "text-color" : "#C3755F",
            "selected-text-color" : "#C3755F"
        },
        "Char": {
            "text-color" : "#D4944F",
            "selected-text-color" : "#D4944F"
        },
        "Comment": {
            "text-color" : "#95A39D",
            "selected-text-color" : "#95A39D"
        },
        "CommentVar" : {
            "text-color" : "#95A39D",
            "selected-text-color" : "#95A39D"
        },
        "Constant" : {
            "text-color" : "#679E95",
            "selected-text-color" : "#679E95"
        },
        "ControlFlow" : {
            "text-color" : "#77966C",
            "selected-text-color" : "#77966C"
        },
        "DataType" : {
            "text-color" : "#738093",
            "selected-text-color" : "#738093"
        },
        "DecVal" : {
            "text-color" : "#AD7583",
            "selected-text-color" : "#AD7583"
        },
        "Documentation" : {
            "text-color" : "#95A39D",
            "selected-text-color" : "#95A39D"
        },
        "Error" : {
            "text-color" : "#C3755F",
            "selected-text-color" : "#C3755F"
        },
        "Extension" : {
            "text-color" : "#AD7583",
            "selected-text-color" : "#AD7583"
        },
        "Float" : {
            "text-color" : "#AD7583",
            "selected-text-color" : "#AD7583"
        },
        "Function" : {
            "text-color" : "#C3755F",
            "selected-text-color" : "#C3755F"
        },
        "Import" : {
            "text-color" : "#738093",
            "selected-text-color" : "#738093"
        },
        "Information" : {
            "text-color" : "#95A39D",
            "selected-text-color" : "#95A39D"
        },
        "Keyword" : {
            "text-color" : "#77966C",
            "selected-text-color" : "#77966C"
        },
        "Normal" : {
            "text-color" : "#CBD2CF",
            "selected-text-color" : "#CBD2CF",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#679E95",
            "selected-text-color" : "#679E95"
        },
        "Others" : {
            "text-color" : "#AD7583",
            "selected-text-color" : "#AD7583"
        },
        "Preprocessor" : {
            "text-color" : "#738093",
            "selected-text-color" : "#738093"
        },
        "RegionMarker" : {
            "text-color" : "#738093",
            "selected-text-color" : "#738093"
        },
        "SpecialChar" : {
            "text-color" : "#D4944F",
            "selected-text-color" : "#D4944F"
        },
        "SpecialString" : {
            "text-color" : "#D4944F",
            "selected-text-color" : "#D4944F"
        },
        "String" : {
            "text-color" : "#D4944F",
            "selected-text-color" : "#D4944F"
        },
        "Variable" : {
            "text-color" : "#679E95",
            "selected-text-color" : "#679E95"
        },
        "VerbatimString" : {
            "text-color" : "#D4944F",
            "selected-text-color" : "#D4944F"
        },
        "Warning" : {
            "text-color" : "#C3755F",
            "selected-text-color" : "#C3755F"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#292F2C",
        "BracketMatching" : "#677770",
        "CodeFolding" : "#677770",
        "CurrentLine" : "#57655E",
        "CurrentLineNumber" : "#95A39D",
        "IconBorder" : "#333B37",
        "IndentationLine" : "#95A39D",
        "LineNumbers" : "#95A39D",
        "MarkBookmark" : "#77966C",
        "MarkBreakpointActive" : "#77966C",
        "MarkBreakpointDisabled" : "#677770",
        "MarkBreakpointReached" : "#AD7583",
        "MarkError" : "#C3755F",
        "MarkExecution" : "#677770",
        "MarkWarning" : "#D4944F",
        "ModifiedLines" : "#C3755F",
        "ReplaceHighlight" : "#677770",
        "SavedLines" : "#77966C",
        "SearchHighlight" : "#677770",
        "Separator" : "#292F2C",
        "SpellChecking" : "#C3755F",
        "TabMarker" : "#333B37",
        "TemplateBackground" : "#404A45",
        "TemplateFocusedPlaceholder" : "#AD7583",
        "TemplatePlaceholder" : "#77966C",
        "TemplateReadOnlyPlaceholder" : "#D4944F",
        "TextSelection" : "#677770",
        "WordWrapMarker" : "#404A45"
    }
}
