{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "solarpunk",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#d65c5e",
            "selected-text-color" : "#d65c5e",
            "background-color" : "#1B2B31"
        },
        "Annotation": {
            "text-color" : "#ADB298",
            "selected-text-color" : "#ADB298"
        },
        "Attribute" : {
            "text-color" : "#F0F3BD",
            "selected-text-color" : "#F0F3BD"
        },
        "BaseN": {
            "text-color" : "#F0F3BD",
            "selected-text-color" : "#F0F3BD"
        },
        "BuiltIn": {
            "text-color" : "#d65c5e",
            "selected-text-color" : "#d65c5e"
        },
        "Char": {
            "text-color" : "#ebba47",
            "selected-text-color" : "#ebba47"
        },
        "Comment": {
            "text-color" : "#ADB298",
            "selected-text-color" : "#ADB298"
        },
        "CommentVar" : {
            "text-color" : "#ADB298",
            "selected-text-color" : "#ADB298"
        },
        "Constant" : {
            "text-color" : "#61d1b1",
            "selected-text-color" : "#61d1b1"
        },
        "ControlFlow" : {
            "text-color" : "#afe085",
            "selected-text-color" : "#afe085"
        },
        "DataType" : {
            "text-color" : "#61a6d1",
            "selected-text-color" : "#61a6d1"
        },
        "DecVal" : {
            "text-color" : "#F0F3BD",
            "selected-text-color" : "#F0F3BD"
        },
        "Documentation" : {
            "text-color" : "#ADB298",
            "selected-text-color" : "#ADB298"
        },
        "Error" : {
            "text-color" : "#d65c5e",
            "selected-text-color" : "#d65c5e"
        },
        "Extension" : {
            "text-color" : "#F0F3BD",
            "selected-text-color" : "#F0F3BD"
        },
        "Float" : {
            "text-color" : "#F0F3BD",
            "selected-text-color" : "#F0F3BD"
        },
        "Function" : {
            "text-color" : "#d65c5e",
            "selected-text-color" : "#d65c5e"
        },
        "Import" : {
            "text-color" : "#61a6d1",
            "selected-text-color" : "#61a6d1"
        },
        "Information" : {
            "text-color" : "#ADB298",
            "selected-text-color" : "#ADB298"
        },
        "Keyword" : {
            "text-color" : "#afe085",
            "selected-text-color" : "#afe085"
        },
        "Normal" : {
            "text-color" : "#DADED3",
            "selected-text-color" : "#DADED3",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#61d1b1",
            "selected-text-color" : "#61d1b1"
        },
        "Others" : {
            "text-color" : "#F0F3BD",
            "selected-text-color" : "#F0F3BD"
        },
        "Preprocessor" : {
            "text-color" : "#61a6d1",
            "selected-text-color" : "#61a6d1"
        },
        "RegionMarker" : {
            "text-color" : "#61a6d1",
            "selected-text-color" : "#61a6d1"
        },
        "SpecialChar" : {
            "text-color" : "#ebba47",
            "selected-text-color" : "#ebba47"
        },
        "SpecialString" : {
            "text-color" : "#ebba47",
            "selected-text-color" : "#ebba47"
        },
        "String" : {
            "text-color" : "#ebba47",
            "selected-text-color" : "#ebba47"
        },
        "Variable" : {
            "text-color" : "#61d1b1",
            "selected-text-color" : "#61d1b1"
        },
        "VerbatimString" : {
            "text-color" : "#ebba47",
            "selected-text-color" : "#ebba47"
        },
        "Warning" : {
            "text-color" : "#d65c5e",
            "selected-text-color" : "#d65c5e"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#1B2B31",
        "BracketMatching" : "#617A83",
        "CodeFolding" : "#617A83",
        "CurrentLine" : "#4B5F66",
        "CurrentLineNumber" : "#ADB298",
        "IconBorder" : "#243941",
        "IndentationLine" : "#ADB298",
        "LineNumbers" : "#ADB298",
        "MarkBookmark" : "#afe085",
        "MarkBreakpointActive" : "#afe085",
        "MarkBreakpointDisabled" : "#617A83",
        "MarkBreakpointReached" : "#F0F3BD",
        "MarkError" : "#d65c5e",
        "MarkExecution" : "#617A83",
        "MarkWarning" : "#ebba47",
        "ModifiedLines" : "#d65c5e",
        "ReplaceHighlight" : "#617A83",
        "SavedLines" : "#afe085",
        "SearchHighlight" : "#617A83",
        "Separator" : "#1B2B31",
        "SpellChecking" : "#d65c5e",
        "TabMarker" : "#243941",
        "TemplateBackground" : "#2E4851",
        "TemplateFocusedPlaceholder" : "#F0F3BD",
        "TemplatePlaceholder" : "#afe085",
        "TemplateReadOnlyPlaceholder" : "#ebba47",
        "TextSelection" : "#617A83",
        "WordWrapMarker" : "#2E4851"
    }
}
