{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "viridian",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#C48696",
            "selected-text-color" : "#C48696",
            "background-color" : "#37382F"
        },
        "Annotation": {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "Attribute" : {
            "text-color" : "#B48AC0",
            "selected-text-color" : "#B48AC0"
        },
        "BaseN": {
            "text-color" : "#B48AC0",
            "selected-text-color" : "#B48AC0"
        },
        "BuiltIn": {
            "text-color" : "#C48696",
            "selected-text-color" : "#C48696"
        },
        "Char": {
            "text-color" : "#D7BE74",
            "selected-text-color" : "#D7BE74"
        },
        "Comment": {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "CommentVar" : {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "Constant" : {
            "text-color" : "#8AC0B2",
            "selected-text-color" : "#8AC0B2"
        },
        "ControlFlow" : {
            "text-color" : "#B3C08A",
            "selected-text-color" : "#B3C08A"
        },
        "DataType" : {
            "text-color" : "#8F8AC0",
            "selected-text-color" : "#8F8AC0"
        },
        "DecVal" : {
            "text-color" : "#B48AC0",
            "selected-text-color" : "#B48AC0"
        },
        "Documentation" : {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "Error" : {
            "text-color" : "#C48696",
            "selected-text-color" : "#C48696"
        },
        "Extension" : {
            "text-color" : "#B48AC0",
            "selected-text-color" : "#B48AC0"
        },
        "Float" : {
            "text-color" : "#B48AC0",
            "selected-text-color" : "#B48AC0"
        },
        "Function" : {
            "text-color" : "#C48696",
            "selected-text-color" : "#C48696"
        },
        "Import" : {
            "text-color" : "#8F8AC0",
            "selected-text-color" : "#8F8AC0"
        },
        "Information" : {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "Keyword" : {
            "text-color" : "#B3C08A",
            "selected-text-color" : "#B3C08A"
        },
        "Normal" : {
            "text-color" : "#d9d3c5",
            "selected-text-color" : "#d9d3c5",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#8AC0B2",
            "selected-text-color" : "#8AC0B2"
        },
        "Others" : {
            "text-color" : "#B48AC0",
            "selected-text-color" : "#B48AC0"
        },
        "Preprocessor" : {
            "text-color" : "#8F8AC0",
            "selected-text-color" : "#8F8AC0"
        },
        "RegionMarker" : {
            "text-color" : "#8F8AC0",
            "selected-text-color" : "#8F8AC0"
        },
        "SpecialChar" : {
            "text-color" : "#D7BE74",
            "selected-text-color" : "#D7BE74"
        },
        "SpecialString" : {
            "text-color" : "#D7BE74",
            "selected-text-color" : "#D7BE74"
        },
        "String" : {
            "text-color" : "#D7BE74",
            "selected-text-color" : "#D7BE74"
        },
        "Variable" : {
            "text-color" : "#8AC0B2",
            "selected-text-color" : "#8AC0B2"
        },
        "VerbatimString" : {
            "text-color" : "#D7BE74",
            "selected-text-color" : "#D7BE74"
        },
        "Warning" : {
            "text-color" : "#C48696",
            "selected-text-color" : "#C48696"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#37382F",
        "BracketMatching" : "#988059",
        "CodeFolding" : "#988059",
        "CurrentLine" : "#816d4c",
        "CurrentLineNumber" : "#b7ac90",
        "IconBorder" : "#43443A",
        "IndentationLine" : "#b7ac90",
        "LineNumbers" : "#b7ac90",
        "MarkBookmark" : "#B3C08A",
        "MarkBreakpointActive" : "#B3C08A",
        "MarkBreakpointDisabled" : "#988059",
        "MarkBreakpointReached" : "#B48AC0",
        "MarkError" : "#C48696",
        "MarkExecution" : "#988059",
        "MarkWarning" : "#D7BE74",
        "ModifiedLines" : "#C48696",
        "ReplaceHighlight" : "#988059",
        "SavedLines" : "#B3C08A",
        "SearchHighlight" : "#988059",
        "Separator" : "#37382F",
        "SpellChecking" : "#C48696",
        "TabMarker" : "#43443A",
        "TemplateBackground" : "#515246",
        "TemplateFocusedPlaceholder" : "#B48AC0",
        "TemplatePlaceholder" : "#B3C08A",
        "TemplateReadOnlyPlaceholder" : "#D7BE74",
        "TextSelection" : "#988059",
        "WordWrapMarker" : "#515246"
    }
}
