{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "viridian",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#bc7486",
            "selected-text-color" : "#bc7486",
            "background-color" : "#373631"
        },
        "Annotation": {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "Attribute" : {
            "text-color" : "#ad7abc",
            "selected-text-color" : "#ad7abc"
        },
        "BaseN": {
            "text-color" : "#ad7abc",
            "selected-text-color" : "#ad7abc"
        },
        "BuiltIn": {
            "text-color" : "#bc7486",
            "selected-text-color" : "#bc7486"
        },
        "Char": {
            "text-color" : "#d2a963",
            "selected-text-color" : "#d2a963"
        },
        "Comment": {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "CommentVar" : {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "Constant" : {
            "text-color" : "#76bfa2",
            "selected-text-color" : "#76bfa2"
        },
        "ControlFlow" : {
            "text-color" : "#92Ba73",
            "selected-text-color" : "#92Ba73"
        },
        "DataType" : {
            "text-color" : "#807abc",
            "selected-text-color" : "#807abc"
        },
        "DecVal" : {
            "text-color" : "#ad7abc",
            "selected-text-color" : "#ad7abc"
        },
        "Documentation" : {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "Error" : {
            "text-color" : "#bc7486",
            "selected-text-color" : "#bc7486"
        },
        "Extension" : {
            "text-color" : "#ad7abc",
            "selected-text-color" : "#ad7abc"
        },
        "Float" : {
            "text-color" : "#ad7abc",
            "selected-text-color" : "#ad7abc"
        },
        "Function" : {
            "text-color" : "#bc7486",
            "selected-text-color" : "#bc7486"
        },
        "Import" : {
            "text-color" : "#807abc",
            "selected-text-color" : "#807abc"
        },
        "Information" : {
            "text-color" : "#b7ac90",
            "selected-text-color" : "#b7ac90"
        },
        "Keyword" : {
            "text-color" : "#92Ba73",
            "selected-text-color" : "#92Ba73"
        },
        "Normal" : {
            "text-color" : "#d9d3c5",
            "selected-text-color" : "#d9d3c5",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#76bfa2",
            "selected-text-color" : "#76bfa2"
        },
        "Others" : {
            "text-color" : "#ad7abc",
            "selected-text-color" : "#ad7abc"
        },
        "Preprocessor" : {
            "text-color" : "#807abc",
            "selected-text-color" : "#807abc"
        },
        "RegionMarker" : {
            "text-color" : "#807abc",
            "selected-text-color" : "#807abc"
        },
        "SpecialChar" : {
            "text-color" : "#d2a963",
            "selected-text-color" : "#d2a963"
        },
        "SpecialString" : {
            "text-color" : "#d2a963",
            "selected-text-color" : "#d2a963"
        },
        "String" : {
            "text-color" : "#d2a963",
            "selected-text-color" : "#d2a963"
        },
        "Variable" : {
            "text-color" : "#76bfa2",
            "selected-text-color" : "#76bfa2"
        },
        "VerbatimString" : {
            "text-color" : "#d2a963",
            "selected-text-color" : "#d2a963"
        },
        "Warning" : {
            "text-color" : "#bc7486",
            "selected-text-color" : "#bc7486"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#373631",
        "BracketMatching" : "#988059",
        "CodeFolding" : "#988059",
        "CurrentLine" : "#816d4c",
        "CurrentLineNumber" : "#b7ac90",
        "IconBorder" : "#45443d",
        "IndentationLine" : "#b7ac90",
        "LineNumbers" : "#b7ac90",
        "MarkBookmark" : "#92Ba73",
        "MarkBreakpointActive" : "#92Ba73",
        "MarkBreakpointDisabled" : "#988059",
        "MarkBreakpointReached" : "#ad7abc",
        "MarkError" : "#bc7486",
        "MarkExecution" : "#988059",
        "MarkWarning" : "#d2a963",
        "ModifiedLines" : "#bc7486",
        "ReplaceHighlight" : "#988059",
        "SavedLines" : "#92Ba73",
        "SearchHighlight" : "#988059",
        "Separator" : "#373631",
        "SpellChecking" : "#bc7486",
        "TabMarker" : "#45443d",
        "TemplateBackground" : "#515048",
        "TemplateFocusedPlaceholder" : "#ad7abc",
        "TemplatePlaceholder" : "#92Ba73",
        "TemplateReadOnlyPlaceholder" : "#d2a963",
        "TextSelection" : "#988059",
        "WordWrapMarker" : "#515048"
    }
}
