{
    "metadata" : {
        "copyright" : ["SPDX-FileCopyrightText: fm3chanic <f.m3chanic@gmail.com>"],
        "license" : "SPDX-License-Identifier: MIT",
        "name" : "viridian",
        "revision" : 1
    },
    "text-styles" : {
        "Alert" : {
            "text-color" : "#c17b71",
            "selected-text-color" : "#c17b71",
            "background-color" : "#2b2f29"
        },
        "Annotation": {
            "text-color" : "#bfbc95",
            "selected-text-color" : "#bfbc95"
        },
        "Attribute" : {
            "text-color" : "#b27bb8",
            "selected-text-color" : "#b27bb8"
        },
        "BaseN": {
            "text-color" : "#b27bb8",
            "selected-text-color" : "#b27bb8"
        },
        "BuiltIn": {
            "text-color" : "#c17b71",
            "selected-text-color" : "#c17b71"
        },
        "Char": {
            "text-color" : "#c0a659",
            "selected-text-color" : "#c0a659"
        },
        "Comment": {
            "text-color" : "#bfbc95",
            "selected-text-color" : "#bfbc95"
        },
        "CommentVar" : {
            "text-color" : "#bfbc95",
            "selected-text-color" : "#bfbc95"
        },
        "Constant" : {
            "text-color" : "#5fbab5",
            "selected-text-color" : "#5fbab5"
        },
        "ControlFlow" : {
            "text-color" : "#a2b77a",
            "selected-text-color" : "#a2b77a"
        },
        "DataType" : {
            "text-color" : "#8d7bb8",
            "selected-text-color" : "#8d7bb8"
        },
        "DecVal" : {
            "text-color" : "#b27bb8",
            "selected-text-color" : "#b27bb8"
        },
        "Documentation" : {
            "text-color" : "#bfbc95",
            "selected-text-color" : "#bfbc95"
        },
        "Error" : {
            "text-color" : "#c17b71",
            "selected-text-color" : "#c17b71"
        },
        "Extension" : {
            "text-color" : "#b27bb8",
            "selected-text-color" : "#b27bb8"
        },
        "Float" : {
            "text-color" : "#b27bb8",
            "selected-text-color" : "#b27bb8"
        },
        "Function" : {
            "text-color" : "#c17b71",
            "selected-text-color" : "#c17b71"
        },
        "Import" : {
            "text-color" : "#8d7bb8",
            "selected-text-color" : "#8d7bb8"
        },
        "Information" : {
            "text-color" : "#bfbc95",
            "selected-text-color" : "#bfbc95"
        },
        "Keyword" : {
            "text-color" : "#a2b77a",
            "selected-text-color" : "#a2b77a"
        },
        "Normal" : {
            "text-color" : "#efeddc",
            "selected-text-color" : "#efeddc",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Operator" : {
            "text-color" : "#5fbab5",
            "selected-text-color" : "#5fbab5"
        },
        "Others" : {
            "text-color" : "#b27bb8",
            "selected-text-color" : "#b27bb8"
        },
        "Preprocessor" : {
            "text-color" : "#8d7bb8",
            "selected-text-color" : "#8d7bb8"
        },
        "RegionMarker" : {
            "text-color" : "#8d7bb8",
            "selected-text-color" : "#8d7bb8"
        },
        "SpecialChar" : {
            "text-color" : "#c0a659",
            "selected-text-color" : "#c0a659"
        },
        "SpecialString" : {
            "text-color" : "#c0a659",
            "selected-text-color" : "#c0a659"
        },
        "String" : {
            "text-color" : "#c0a659",
            "selected-text-color" : "#c0a659"
        },
        "Variable" : {
            "text-color" : "#5fbab5",
            "selected-text-color" : "#5fbab5"
        },
        "VerbatimString" : {
            "text-color" : "#c0a659",
            "selected-text-color" : "#c0a659"
        },
        "Warning" : {
            "text-color" : "#c17b71",
            "selected-text-color" : "#c17b71"
        }
    },
    "editor-colors": {
        "BackgroundColor" : "#2b2f29",
        "BracketMatching" : "#687162",
        "CodeFolding" : "#687162",
        "CurrentLine" : "#575f52",
        "CurrentLineNumber" : "#bfbc95",
        "IconBorder" : "#373c34",
        "IndentationLine" : "#bfbc95",
        "LineNumbers" : "#bfbc95",
        "MarkBookmark" : "#a2b77a",
        "MarkBreakpointActive" : "#a2b77a",
        "MarkBreakpointDisabled" : "#687162",
        "MarkBreakpointReached" : "#b27bb8",
        "MarkError" : "#c17b71",
        "MarkExecution" : "#687162",
        "MarkWarning" : "#c0a659",
        "ModifiedLines" : "#c17b71",
        "ReplaceHighlight" : "#687162",
        "SavedLines" : "#a2b77a",
        "SearchHighlight" : "#687162",
        "Separator" : "#2b2f29",
        "SpellChecking" : "#c17b71",
        "TabMarker" : "#373c34",
        "TemplateBackground" : "#454b41",
        "TemplateFocusedPlaceholder" : "#b27bb8",
        "TemplatePlaceholder" : "#a2b77a",
        "TemplateReadOnlyPlaceholder" : "#c0a659",
        "TextSelection" : "#687162",
        "WordWrapMarker" : "#454b41"
    }
}
